### ISSUE TITLE
CSV data loader

### ISSUE THREAD

**Issue by pwalsh** [openspending/fiscal-data-js#1]
# Description

The `stateTree`, which holds all data in the `fiscalData` lib, can potentially be populated from any `dataSource` via a `loader`.

Additionally, the `stateTree` can be updated based on user interaction after the initial population of the `stateTree`.

In the `fiscalData` lib, we want to ship with two loaders (and allow custom loaders in the future):

* CSV: a loader to populate the `stateTree` from a CSV data source (this issue)
* FDP: a loader to populate the `stateTree` from a [Fiscal Data Package](http://fiscal.dataprotocols.org/spec/) #6

# Tasks

I'm made a start on this loader. The [current implementation is here](https://github.com/openspending/fiscal-data-js/blob/master/lib/loaders/index.js#L47). [An example of how this loader is used can be seen here, in the function called to initialise the `stateTree`](https://github.com/openspending/fiscal-data-js/blob/master/lib/actions/index.js#L64).

* [x] Read `model` and `ui` configuration from the passed options object
* [x] Parse the dataSource into JSON, stored in `data.values` in the `stateTree`
  * [x] As plain CSV has no schema for types, infer the schema and convert the data values to the inferred types using [json-table-schema-js](https://github.com/okfn/jsontableschema-js/blob/master/infer.js)
* [x] Extract headers from the data into `data.headers` in the `stateTree`
* [x] Extract the current state from the data into `data.states.current` in the `stateTree`. The current state is a *representation* of the data, based on the `ui.selections` which filter and group the raw data using the declared `dimensions`
* [x] Update the current state, based on user actions, and maintain the state history in `data.states.past` and `data.states.future`, [using this pattern](http://rackt.org/redux/docs/recipes/ImplementingUndoHistory.html). Also [this existing lib may help, or not](https://github.com/johanneslumpe/redux-history-transitions) (flag with @pwalsh is there are any possible problems with this pattern)
* [x] Write unit tests for all functions/functionality of the loader

**Important Note**: In this implementation, we are presuming that all data is read from the CSV `dataSource` and stored in the `stateTree` as `data.values`. That means that updates to the current state can perform filtering/grouping/etc. on `data.values` directly. 

However, I acknowledge that over a certain size of file for the `dataSource`, this may become impossible, in which case we'd need to do implement different functions for filtering and grouping, by re-reading the stream from the data source and not holding all data in `data.values`. 

The important point to note here is that in the next iteration, **functions for filtering and grouping to build the current state may need to be configurable (e.g.: custom functions passed in)**.

**Comment by pwalsh** [comment]
DONE
