### ISSUE TITLE
New spec for dimension attributes: `parent`

### ISSUE THREAD

**Issue by pwalsh** [openspending/fiscal-data-js#11]
# Description

Dimension attributes are changing.

This:

```
    "dimensions": {
      "date": {
        "dimensionType": "datetime",
        "attributes": [
          { "year": { "source": "YEAR" } }
        ]
      },
      "economic-classification": {
        "dimensionType": "classification",
        "classificationType": "economic",
        "attributes": [
          { "econ4": { "source": "ECON4" } },
          { "econ5": { "source": "ECON5" } }
        ]
      },
      "administrative-classification": {
        "dimensionType": "classification",
        "classificationType": "administrative",
        "attributes": [
          { "admin1": { "source": "ADMIN1" }
          },
          { "admin2": { "source": "ADMIN2" } }
        ]
      }
    }
  }
```

becomes:

```
    "dimensions": {
      "date": {
        "dimensionType": "datetime",
        "attributes": {
          "year": { "source": "YEAR" }
        }
      },
      "economic-classification": {
        "dimensionType": "classification",
        "classificationType": "economic",
        "attributes": {
          "econ4": { "source": "ECON4" },
          "econ5": { "source": "ECON5", "parent": "econ4" }
        }
      },
      "administrative-classification": {
        "dimensionType": "classification",
        "classificationType": "administrative",
        "attributes": {
          "admin1": { "source": "ADMIN1" },
          "admin2": { "source": "ADMIN2", "parent": "admin1" }
        }
      }
    }
  }
```

# Tasks

* [ ] Dimensions are just the top level properties of `dimensions` - not their nested attributes (currently that is what we do - treat all attributes as distinct dimensions). Ensure that we reflect this when we read from the resource into our new representation of the data
* [ ] The name of a dimension is its key
* [ ] A denormalised dimension across multiple fields should get normalised into a parent/child structure
