### ISSUE TITLE
Implement a prototype view using the first iteration of the library

### ISSUE THREAD

**Issue by pwalsh** [openspending/fiscal-data-js#3]
# Tasks

* [x] Treemap
* [x] Display code lists
* [x] Update data based on user interactions with code lists and visualisation itself
* [x] Navigate across state history

**Comment by pwalsh** [comment]
Closing. This is actually https://github.com/openspending/fiscal-data-package-viewer
