### ISSUE TITLE
Fiscal Data Package data loader

### ISSUE THREAD

**Issue by pwalsh** [openspending/fiscal-data-js#6]
# Description

The `stateTree`, which holds all data in the `fiscalData` lib, can potentially be populated from any `dataSource` via a `loader`.

Additionally, the `stateTree` can be updated based on user interaction after the initial population of the `stateTree`.

In the `fiscalData` lib, we want to ship with two loaders (and allow custom loaders in the future):

* CSV: a loader to populate the `stateTree` from a CSV data source #1 
* FDP: a loader to populate the `stateTree` from a [Fiscal Data Package](http://fiscal.dataprotocols.org/spec/) (this issue)

# Tasks

* [x] Read `model` configuration from the Fiscal Data Package `mapping` object
* [x] Read `ui` configuration from the passed options object, or, build the selections automatically from the `model` (e.g.: take first measure as selected, take first value of first dimension as selected)
* [x] Parse the `resources` from the Data Package into JSON, stored in `data.values` in the `stateTree`
  * [x] We only support **one resource** for this implementation
  * [x] All resources have a `schema`: convert the data to the appropriate `type`
* [x] Extract headers from the data into `data.headers` in the `stateTree`
* [x] Extract the current state from the data into `data.states.current` in the `stateTree`. The current state is a *representation* of the data, based on the `ui.selections` which filter and group the raw data using the declared `dimensions`
* [x] Update the current state, based on user actions, and maintain the state history in `data.states.past` and `data.states.future`, [using this pattern](http://rackt.org/redux/docs/recipes/ImplementingUndoHistory.html). Also [this existing lib may help, or not](https://github.com/johanneslumpe/redux-history-transitions) (flag with @pwalsh is there are any possible problems with this pattern)
* [x] Write unit tests for all functions/functionality of the loader

**Comment by pwalsh** [comment]
DONE.
